name: Build and publish project

# This part must be uncommented
#on:
#  push:
#    tags:
#      - '**'

# Check if the workflow work (this part will be removed):
on:
  push

jobs:
  buildForAllSupportedPlatforms:
    name: Build.yml workflow for '${{ matrix.targetPlatform }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # See 'game-ci/unity-builder' docs for an overview of the available platforms
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
          - WebGL
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache libraries
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build noclip for '${{ matrix.targetPlatform }}'
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload noclip build artifact for '${{ matrix.targetPlatform }}'
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}